credentials:
  usernames:
    admin:
      email: trungcntt96@gmail.com
      name: John Smith
      password: admin # To be replaced with hashed password
    rbriggs:
      email: trungcntt96@gmail.com
      name: Rebecca Briggs
      password: def # To be replaced with hashed password0
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com